// src/styles/ScannerInterfaceStyles.js
import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'black' },
  permissionContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f5f5f5', padding: 20 },
  permissionText: { fontSize: 16, color: '#666', textAlign: 'center', marginBottom: 10 },
  permissionSubtext: { fontSize: 14, color: '#999', textAlign: 'center', marginBottom: 20 },
  header: { position: 'absolute', top: 50, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-around', zIndex: 10 },
  headerText: { color: 'white', fontSize: 16, fontWeight: 'bold', backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  defectBannerActive: { position: 'absolute', top: 90, alignSelf: 'center', backgroundColor: '#ff5722', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8, zIndex: 10, alignItems: 'center' },
  defectText: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  defectSubtext: { color: 'rgba(255,255,255,0.9)', fontSize: 11, marginTop: 2 },
  overlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.3)' },
  scanFrame: { width: 250, height: 250, borderWidth: 2, borderColor: '#00ff44', borderRadius: 10 },
  corner: { position: 'absolute', width: 30, height: 30, borderColor: '#00ff44' },
  cornerTopLeft: { top: -2, left: -2, borderTopWidth: 4, borderLeftWidth: 4, borderTopLeftRadius: 10 },
  cornerTopRight: { top: -2, right: -2, borderTopWidth: 4, borderRightWidth: 4, borderTopRightRadius: 10 },
  cornerBottomLeft: { bottom: -2, left: -2, borderBottomWidth: 4, borderLeftWidth: 4, borderBottomLeftRadius: 10 },
  cornerBottomRight: { bottom: -2, right: -2, borderBottomWidth: 4, borderRightWidth: 4, borderBottomRightRadius: 10 },
  scanLine: { position: 'absolute', width: '80%', height: 2, backgroundColor: '#00ff44', opacity: 0.9 },
  feedbackCircle: { position: 'absolute', top: '45%', left: '50%', marginLeft: -30, width: 60, height: 60, borderRadius: 30, zIndex: 9999, opacity: 0.9, pointerEvents: 'none' },
  buttonContainer: { position: 'absolute', bottom: 80, left: 16, right: 16, flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  labelContainer: { position: 'absolute', bottom: 40, left: 16, right: 16, flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  buttonLabel: { flex: 1, textAlign: 'center', color: 'white', fontSize: 10, backgroundColor: 'rgba(0,0,0,0.4)', paddingVertical: 4, borderRadius: 4 },
  defectLabel: { color: '#ff9800', fontWeight: 'bold' },
  button: { flex: 1, paddingVertical: 14, paddingHorizontal: 8, backgroundColor: '#2196F3', borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  activeButton: { backgroundColor: '#4CAF50', shadowColor: '#4CAF50', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.8, shadowRadius: 10 },
  defectButton: { backgroundColor: '#ff9800' },
  defectButtonActive: { backgroundColor: '#f44336', borderWidth: 2, borderColor: '#fff' },
  defectuosoButton: { backgroundColor: '#9C27B0' },
  finalizarButton: { backgroundColor: '#ff6b6b' },
  buttonText: { color: 'white', fontWeight: 'bold', fontSize: 18 },
  // ✅ ESTILOS PARA MODAL DE CONFIRMACIÓN DE SALIDA
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: 'white', borderRadius: 16, padding: 24, width: '85%', maxWidth: 400, elevation: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 4 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 16, textAlign: 'center', color: '#333' },
  modalMessage: { fontSize: 16, color: '#666', textAlign: 'center', marginBottom: 20, lineHeight: 22 },
  modalStats: { backgroundColor: '#f9f9f9', padding: 12, borderRadius: 8, marginBottom: 16 },
  statItem: { fontSize: 14, color: '#333', marginBottom: 4 },
  statValue: { fontWeight: 'bold', color: '#2196F3' },
  warningText: { fontSize: 13, color: '#f44336', marginTop: 8, fontStyle: 'italic' },
  modalNote: { fontSize: 12, color: '#888', textAlign: 'center', marginBottom: 20, fontStyle: 'italic' },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  modalButton: { flex: 1, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 8, alignItems: 'center' },
  cancelButton: { backgroundColor: '#6c757d' },
  cancelButtonText: { color: 'white', fontWeight: '600', fontSize: 14 },
  confirmButton: { backgroundColor: '#2196F3' },
  confirmButtonText: { color: 'white', fontWeight: '600', fontSize: 14 },
  modalList: { maxHeight: 250, marginBottom: 16 },
  productoItem: { padding: 15, backgroundColor: '#f9f9f9', borderRadius: 8, marginBottom: 8 },
  productoItemText: { fontSize: 16, fontWeight: '600', color: '#333' },
  productoItemDetail: { fontSize: 12, color: '#666', marginTop: 4 },
  input: { borderWidth: 2, borderColor: '#ddd', padding: 16, borderRadius: 10, fontSize: 20, marginBottom: 20, textAlign: 'center', backgroundColor: '#f9f9f9' },
});
export { styles };